blank_issues_enabled: true
contact_links:
  - name: 🤔 Questions & Discussions
    url: https://github.com/techor-dev/techor/discussions
    about: Use GitHub discussions for forum-like discussions and questions.
