name: Check title of pull request
on:
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    check:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - name: Techor Actions
              uses: 1aron/techor@v2.5.3
              with:
                  action: "check-pull-request-title"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
