name: Release
on:
    push:
        branches:
            - main
            - beta

jobs:
    release:
        timeout-minutes: 15
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: pnpm/action-setup@v3
              with:
                  version: 8
            - uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "pnpm"
            - run: pnpm install
            - run: pnpm run build
            - uses: lewagon/wait-on-check-action@v1.3.1
              with:
                  ref: ${{ github.ref }}
                  running-workflow-name: wait-for-check-regexp
                  check-regexp: lint|test|commit-check|type-check
                  repo-token: ${{ secrets.GITHUB_TOKEN }}
                  wait-interval: 10
            - run: pnpm exec semantic-release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
