name: Sync dev branches
on:
    push:
        branches:
            - "*"

jobs:
    check:
        timeout-minutes: 15
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: "pnpm"
            - name: Techor Actions
              uses: 1aron/techor@v2.4.6
              with:
                  action: "sync-dev-branches"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
