name: Sync dev branches
on:
    push:
        branches:
            - "*"

jobs:
    check:
        timeout-minutes: 20
        runs-on: ubuntu-20.04
        strategy:
            matrix:
                node-version: [18.17.0]
        steps:
            - uses: actions/checkout@v3
            - name: Sync dev branches
              uses: 1aron/techor@v2.5.14
              with:
                  action: "sync-dev-branches"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
