name: Sync dev branches
on:
    push:
        branches:
            - "*"

jobs:
    sync:
        timeout-minutes: 20
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        steps:
            - uses: actions/checkout@v4
            - uses: ./.github/actions
              with:
                  action: "sync-dev-branches"
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
