name: Test
on:
    push:
        branches:
            - "**"
    pull_request_target:
        types:
            - opened
            - reopened
            - edited
            - synchronize

jobs:
    test:
        timeout-minutes: 15
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [18]
                os: [ubuntu-latest, windows-latest]
        steps:
            - uses: actions/checkout@v3
            - uses: pnpm/action-setup@v2
              with:
                  version: 8
            - uses: actions/setup-node@v3
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'pnpm'
            - run: pnpm install
            - run: pnpm run build
            - run: pnpm test
